const localData = [
    {
      id: 1,
      from: ' Litenburg',
      imgper: '/assets/person.png',
      imgcar: '/assets/audi.jpg',
      name: 'Karabo',
      car: 'Mazda',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '',
      destination: 'Mafikeng',
      accountholder: '',
      phones: '',
      whatsapp: '',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    },
    {
      id: 2,
      from: 'Zeerust ',
      imgper: '/assets/person.png',
      imgcar: '/assets/thebeberian.jpg',
      name: 'Thabo',
      car: 'Beberian',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '',
      destination: 'Brits',
      accountholder: '',
      phones: '',
      whatsapp: '',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    },
    {
      id: 3,
      from: 'Rusternburg',
      imgper: '/assets/person.png',
      imgcar: '/assets/volvo.jpg',
      name: 'John',
      car: 'Volvo',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '123456789',
      destination: 'Pretoria',
      accountholder: 'maobakg@yahoo.com2',
      phones: '0780387163',
      whatsapp: '076 176 27 29',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    },
    {
      id: 4,
      from: 'Mafikeng',
      imgper: '/assets/person.png',
      imgcar: '/assets/Opel.jpg',
      name: 'Tshepo',
      car: 'Opel',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '',
      destination: 'Zeerust',
      accountholder: '',
      phones: '',
      whatsapp: '',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    },
    {
      id: 5,
      from: 'Rustenburg',
      imgper: '/assets/person.png',
      imgcar: '/assets/Nissan-370Z.jpg',
      name: 'Goerge',
      car: 'Nissan',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '',
      destination: 'Mogwase',
      accountholder: '',
      phones: '',
      whatsapp: '',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    },
    {
      id: 6,
      from: 'Zeerust',
      imgper: '/assets/person.png',
      imgcar: '/assets/audi.jpg',
      name: 'Refilwe',
      car: 'Mazda',
      Seatsavailable: 3,
      Available: '09:10:2023',
      date: '12:30',
      about: '',
      pasword: '',
      destination: 'Brits',
      accountholder: '',
      phones: '',
      whatsapp: '',
      make: '',
      model: '',
      colour: '',
      seats: 0,
      plates: '',
      time: ''
    }
  ]


  module.exports = localData;